# Generated by Django 6.0.6 on 2026-06-10 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('grid_buy_peak', 'grid_buy_peak'), ('grid_buy_valley', 'grid_buy_valley'), ('grid_buy_shoulder', 'grid_buy_shoulder'), ('grid_sell', 'grid_sell')], max_length=50)),
                ('price', models.FloatField(help_text='yuan/kWh')),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('rated_power', models.FloatField(help_text='kW')),
                ('efficiency', models.FloatField(help_text='%')),
                ('api_endpoint', models.CharField(blank=True, default='', max_length=500)),
                ('api_key', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_kwh', models.FloatField(default=0)),
                ('peak_kwh', models.FloatField(default=0)),
                ('valley_kwh', models.FloatField(default=0)),
                ('shoulder_kwh', models.FloatField(default=0)),
                ('self_use_kwh', models.FloatField(default=0, help_text='kWh from solar used by household')),
                ('grid_buy_kwh', models.FloatField(default=0, help_text='kWh bought from grid')),
                ('grid_sell_kwh', models.FloatField(default=0, help_text='kWh sold to grid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='SolarPanelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity_kw', models.FloatField()),
                ('install_angle', models.FloatField(help_text='degrees')),
                ('azimuth', models.FloatField(default=180, help_text='degrees, 180=south')),
                ('grid_date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inverter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_groups', to='solar.inverter')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RevenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('generation_kwh', models.FloatField(default=0)),
                ('self_use_kwh', models.FloatField(default=0)),
                ('grid_sell_kwh', models.FloatField(default=0)),
                ('self_use_saving', models.FloatField(default=0, help_text='yuan saved by self-use')),
                ('grid_sell_income', models.FloatField(default=0, help_text='yuan earned from selling to grid')),
                ('total_income', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to='solar.solarpanelgroup')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'panel_group')},
            },
        ),
        migrations.CreateModel(
            name='DailyGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual_kwh', models.FloatField(default=0)),
                ('theoretical_kwh', models.FloatField(default=0)),
                ('peak_kwh', models.FloatField(default=0, help_text='kWh generated during peak hours')),
                ('valley_kwh', models.FloatField(default=0, help_text='kWh generated during valley hours')),
                ('sunshine_hours', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='solar.solarpanelgroup')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('panel_group', 'date')},
            },
        ),
    ]
