# Generated by Django 6.0.6 on 2026-06-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('panel_group', '光伏板组'), ('inverter', '逆变器')], max_length=20)),
                ('device_id', models.IntegerField()),
                ('device_name', models.CharField(default='', max_length=200)),
                ('date', models.DateField()),
                ('health_score', models.FloatField(default=100, help_text='0-100')),
                ('anomaly_type', models.CharField(choices=[('none', '无异常'), ('low_generation', '发电量偏低'), ('efficiency_drop', '逆变器效率下降'), ('consecutive_low', '连续低发电'), ('grid_issue', '并网异常'), ('peak_valley_abnormal', '峰谷分布异常'), ('deviation_high', '实际/理论偏差过大')], default='none', max_length=30)),
                ('anomaly_level', models.CharField(choices=[('normal', '正常'), ('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='normal', max_length=20)),
                ('possible_cause', models.TextField(blank=True, default='')),
                ('handling_suggestion', models.TextField(blank=True, default='')),
                ('deviation_rate', models.FloatField(default=0, help_text='actual/theoretical deviation %')),
                ('inverter_efficiency', models.FloatField(default=0, help_text='%')),
                ('consecutive_low_days', models.IntegerField(default=0)),
                ('grid_days', models.IntegerField(default=0)),
                ('peak_valley_ratio', models.FloatField(default=0, help_text='peak/valley ratio')),
                ('is_handled', models.BooleanField(default=False)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-anomaly_level'],
                'unique_together': {('device_type', 'device_id', 'date')},
            },
        ),
    ]
