# Generated by Django 6.0.6 on 2026-06-11 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_healthdiagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('capacity_kwh', models.FloatField(help_text='额定容量 kWh')),
                ('max_charge_power_kw', models.FloatField(help_text='最大充电功率 kW')),
                ('max_discharge_power_kw', models.FloatField(help_text='最大放电功率 kW')),
                ('charge_efficiency', models.FloatField(default=95, help_text='充电效率 %')),
                ('discharge_efficiency', models.FloatField(default=95, help_text='放电效率 %')),
                ('soc_upper_limit', models.FloatField(default=90, help_text='SOC上限 %')),
                ('soc_lower_limit', models.FloatField(default=15, help_text='SOC下限 %')),
                ('enable_date', models.DateField(help_text='启用日期')),
                ('current_soc', models.FloatField(default=50, help_text='当前SOC %')),
                ('status', models.CharField(choices=[('normal', '正常'), ('warning', '告警'), ('maintenance', '维护中')], default='normal', max_length=20)),
                ('warning_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panel_groups', models.ManyToManyField(blank=True, related_name='storage_batteries', to='solar.solarpanelgroup')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StorageSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('initial_soc', models.FloatField(default=50, help_text='初始SOC %')),
                ('final_soc', models.FloatField(default=50, help_text='结束SOC %')),
                ('charge_kwh', models.FloatField(default=0, help_text='实际充电量 kWh')),
                ('discharge_kwh', models.FloatField(default=0, help_text='实际放电量 kWh')),
                ('reduced_curtailment_kwh', models.FloatField(default=0, help_text='弃光减少量 kWh')),
                ('peak_discharge_saving', models.FloatField(default=0, help_text='峰时放电节省电费 元')),
                ('valley_charge_cost', models.FloatField(default=0, help_text='谷时充电成本 元')),
                ('grid_income_change', models.FloatField(default=0, help_text='上网收益变化 元')),
                ('total_profit_diff', models.FloatField(default=0, help_text='储能参与后总收益差额 元')),
                ('hourly_soc', models.JSONField(default=list, help_text='24小时SOC数组')),
                ('hourly_charge_discharge', models.JSONField(default=list, help_text='24小时充放电明细 (正=充电, 负=放电)')),
                ('hourly_detail', models.JSONField(default=dict, help_text='详细小时级数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='solar.storagebattery')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('battery', 'date')},
            },
        ),
    ]
