# Generated by Django 6.0.6 on 2026-06-11 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_storagebattery_storageschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='常规清洁', max_length=200)),
                ('cleaning_method', models.CharField(choices=[('manual', '人工清洁'), ('water', '水洗清洁'), ('dry', '干洗清洁'), ('robot', '机器人清洁'), ('rain', '雨水自洁')], default='manual', max_length=30)),
                ('estimated_cost', models.FloatField(default=0, help_text='预计费用 元')),
                ('actual_cost', models.FloatField(default=0, help_text='实际费用 元')),
                ('operator', models.CharField(blank=True, default='', help_text='执行人员', max_length=100)),
                ('plan_date', models.DateField(help_text='计划日期')),
                ('actual_date', models.DateField(blank=True, help_text='实际完成日期', null=True)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='备注')),
                ('pre_avg_efficiency', models.FloatField(default=0, help_text='清洁前7日平均发电效率 %')),
                ('post_avg_efficiency', models.FloatField(default=0, help_text='清洁后7日平均发电效率 %')),
                ('pre_avg_deviation', models.FloatField(default=0, help_text='清洁前7日平均偏差率 %')),
                ('post_avg_deviation', models.FloatField(default=0, help_text='清洁后7日平均偏差率 %')),
                ('consecutive_low_days', models.IntegerField(default=0, help_text='清洁前连续低发电天数')),
                ('weather_sunshine_coeff', models.FloatField(default=1.0, help_text='天气日照系数')),
                ('health_score_before', models.FloatField(default=0, help_text='清洁前健康评分')),
                ('health_score_after', models.FloatField(default=0, help_text='清洁后健康评分')),
                ('recovered_generation_kwh', models.FloatField(default=0, help_text='发电恢复量 kWh')),
                ('extra_revenue', models.FloatField(default=0, help_text='额外收益 元')),
                ('cost_recovery_days', models.IntegerField(default=0, help_text='费用回收天数')),
                ('effectiveness_level', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '较差'), ('none', '未评估')], default='none', max_length=20)),
                ('evaluation_detail', models.JSONField(default=dict, help_text='评估详细数据')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_plans', to='solar.solarpanelgroup')),
            ],
            options={
                'ordering': ['-plan_date', '-id'],
            },
        ),
    ]
